### ISSUE TITLE
Package name ideas

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/SpectroscoPy#29]
In case #20  fails we need some alternative package names! List ideas here!

**Comment by lemmatum** [comment]
* SpectraPy
* SpectralPy
* PrismPy
* Saha
* SahaPy
* Rydberg
* RydbergPy
* LymanPy
* AtomicSpectroscoPy

**Comment by OneGneissGuy** [comment]
* AbsorptionPy
* AbsorPy
* PySpec
* FraunhoferPy

**Comment by lemmatum** [comment]
I think I'll go for SpectroscoPyx if everyone is happy with that :smiley:

**Comment by OneGneissGuy** [comment]
Nice. May I ask how you came to that?

**Comment by lemmatum** [comment]
@OneGneissGuy well the package is currently SpectroscoPy (because puns), and I've been reading about Cython, which uses .pyx files. So more puns!
