### ISSUE TITLE
Support handling roman numerals

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/SpectroscoPy#38]
We need an easy way to convert between integers and Roman numerals, as much of atomic notation uses Roman numerals to describe charge states.

I've got some initial code for such a module.

**Comment by StanczakDominik** [comment]
There's a package called `roman` that's already used by the main repo. Don't reinvent the wheel!

**Comment by lemmatum** [comment]
@StanczakDominik oh that's handy! Wonder why I didn't find it when I was first searching for a roman numerals package a whiles back.
